apply plugin: 'com.android.library'

android {
    namespace 'com.unity3d.anrwatchdog'

    ndkPath getProperty("unity.androidNdkPath")
    ndkVersion getProperty("unity.androidNdkVersion")
    compileSdk getProperty("unity.targetSdkVersion") as int
    buildToolsVersion getProperty("unity.buildToolsVersion")

    defaultConfig {
        minSdk getProperty("unity.minSdkVersion") as int
        targetSdk getProperty("unity.targetSdkVersion") as int

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static'
            }
        }

        consumerProguardFiles 'proguard-rules.pro'
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.valueOf(getProperty("unity.javaCompatabilityVersion"))
        targetCompatibility JavaVersion.valueOf(getProperty("unity.javaCompatabilityVersion"))
    }
}
